# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f6e40cdd7755c6d8aaab970467e112de1f9fcd4bbb2676472ebeb2e05b983159bd11920a3efc16c59242fecaa6140a62cb2a82026cce2e9380892454c58ab9

test:
  secret_key_base: 3e822b7c56ae3238f5e5d2beff057688dbfe514125841deabe74956ab02c90458b3bd34d150f90607186eff1835e14b4675ff395c0ab8a75cd7b0cb40ce495ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
